version: '3'

services:
  bot:
    build: .
    volumes:
      - '.:/code'
      - './crypto_store/:/code/crypto_store/'
      - './session.txt:/code/session.txt'
    command: 'python src/main.py'
    env_file: '.env'

